# Just here as an example should be delete before merging this PR
version: "3"
services:
  db_recipes-init:
    image: postgres:15-alpine
    volumes:
      - ./postgresql:/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 1000:1000 /data

  db_recipes:
    depends_on:
      db_recipes-init:
        condition: service_completed_successfully
    restart: always
    image: postgres:15-alpine
    user: "1000:1000"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes-init:
    image: postgres:15-alpine
    volumes:
      - staticfiles:/staticfiles
      - ./mediafiles:/mediafiles
    entrypoint:
      - sh
      - -c
      - |
        chown -R 1000:1000 /staticfiles
        chown -R 1000:1000 /mediafiles

  web_recipes:
    depends_on:
      - web_recipes-init
      - db_recipes
    restart: always
    # image: vabene1111/recipes
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      # - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles

  nginx_recipes:
    # image: nginx:mainline-alpine
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    # To test its non running as root:
    # user: 101:101
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      # - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro

volumes:
  nginx_config:
  staticfiles:
